/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.team6.views;

import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Quoc Hung
 */
public class RoomForm extends javax.swing.JFrame {

    /**
     * Creates new form RoomForm
     */
    DefaultTableModel model;
    public RoomForm() {
        initComponents();
        model = (DefaultTableModel) tblPlayersInfo.getModel();
    }
    
    public void changeState(){
        if (btnReady.getText().equals("Ready")) btnReady.setText("Cancel");
        else btnReady.setText("Ready");
    }
    
    public void updateTable(int x){
        if (x == 1){
            int win = (int) model.getValueAt(0, 3);
            int score = (int) model.getValueAt(0, 2);
            
            model.setValueAt(win+1, 0, 3);
            model.setValueAt(score+10, 0, 2);
        } else {
            int win = (int) model.getValueAt(1, 3);
            int score = (int) model.getValueAt(1, 2);
            
            model.setValueAt(win+1, 1, 3);
            model.setValueAt(score+10, 1, 2);
        }
    }
    
    public void setBtnReadyActionListenter(ActionListener log){
        btnReady.addActionListener(log);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlayersInfo = new javax.swing.JTable();
        btnReady = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPlayersInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Username", "Score", "Win"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPlayersInfo);
        if (tblPlayersInfo.getColumnModel().getColumnCount() > 0) {
            tblPlayersInfo.getColumnModel().getColumn(0).setResizable(false);
            tblPlayersInfo.getColumnModel().getColumn(1).setResizable(false);
            tblPlayersInfo.getColumnModel().getColumn(2).setResizable(false);
            tblPlayersInfo.getColumnModel().getColumn(3).setResizable(false);
        }

        btnReady.setText("Ready");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnReady)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReady)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReady;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPlayersInfo;
    // End of variables declaration//GEN-END:variables
}
